# Generated by http://www.infobyip.com/ipbulklookup.php at 20160104 08:01:42
IP,Domain,Location
203.24.148.50,,Australia  07  Armadale
202.58.224.53,,Australia  08  Beechboro
125.7.58.230,mail.centrecare.com.au,Australia  08  Perth
103.18.154.68,,Australia  04  Brisbane
49.197.37.48,pa49-197-37-48.pa.qld.optusnet.com.au,Australia  04  Brisbane
180.76.15.140,baiduspider-180-76-15-140.crawl.baidu.com,China  22  Beijing
203.59.32.36,203-59-32-36.perm.iinet.net.au,Australia  08  Perth
49.197.28.162,pa49-197-28-162.pa.qld.optusnet.com.au,Australia  04  Durack
180.76.15.30,baiduspider-180-76-15-30.crawl.baidu.com,China  22  Beijing
101.190.67.6,,Australia  02  Sydney
203.59.9.91,mail.ieuwa.asn.au,Australia  08  South Perth
101.186.64.254,,Australia  08  Perth
210.18.193.25,,Australia  04  Toowoomba
202.58.224.54,,Australia  08  Beechboro
180.76.15.7,baiduspider-180-76-15-7.crawl.baidu.com,China  22  Beijing
125.254.33.122,122.33.254.125.static.soulaustralia.com.au,Australia  07  Ringwood
180.76.15.18,baiduspider-180-76-15-18.crawl.baidu.com,China  22  Beijing
110.142.192.171,shireo151.lnk.telstra.net,Australia  08  Margaret River
101.182.73.54,CPE-101-182-73-54.lnse1.woo.bigpond.net.au,Australia  07  Melbourne
116.212.192.90,,Australia  08  Camillo
203.44.63.162,,Australia  07  Camberwell
103.18.155.68,,Australia  04  Brisbane
203.153.242.182,242.182-dslgw.amnet.net.au,Australia  08  Perth
180.76.15.138,baiduspider-180-76-15-138.crawl.baidu.com,China  22  Beijing
180.76.15.146,baiduspider-180-76-15-146.crawl.baidu.com,China  22  Beijing
180.76.15.33,baiduspider-180-76-15-33.crawl.baidu.com,China  22  Beijing
116.212.197.33,,Australia  08  Perth
180.76.15.15,baiduspider-180-76-15-15.crawl.baidu.com,China  22  Beijing
60.228.19.63,CPE-60-228-19-63.lns6.ken.bigpond.net.au,Australia  08  Perth
207.46.13.38,msnbot-207-46-13-38.search.msn.com,United States  WA  Redmond
83.71.247.36,,Ireland  07  Dublin
180.76.15.137,baiduspider-180-76-15-137.crawl.baidu.com,China  22  Beijing
101.185.75.166,,Australia  05  Adelaide
54.174.79.43,ec2-54-174-79-43.compute-1.amazonaws.com,United States  VA  Ashburn
180.76.15.6,baiduspider-180-76-15-6.crawl.baidu.com,China  22  Beijing
180.76.15.23,baiduspider-180-76-15-23.crawl.baidu.com,China  22  Beijing
180.76.15.13,baiduspider-180-76-15-13.crawl.baidu.com,China  22  Beijing
180.76.15.9,baiduspider-180-76-15-9.crawl.baidu.com,China  22  Beijing
66.249.79.91,crawl-66-249-79-91.googlebot.com,United States  CA  Mountain View
66.249.79.87,crawl-66-249-79-87.googlebot.com,United States  CA  Mountain View
120.22.28.42,,Australia  04  Brisbane
125.7.106.36,,Australia  01  Barton
146.195.186.59,,Australia
106.68.148.152,106-68-148-152.dyn.iinet.net.au,Australia  08  Perth
59.167.110.197,mail.gosnells.wa.gov.au,Australia  08  Perth
180.76.15.148,baiduspider-180-76-15-148.crawl.baidu.com,China  22  Beijing
58.172.43.81,CPE-58-172-43-81.wqcz1.ken.bigpond.net.au,Australia
118.209.94.30,ppp118-209-94-30.lns20.mel4.internode.on.net,Australia  07  South Morang
120.148.89.242,CPE-120-148-89-242.nhgx1.lon.bigpond.net.au,Australia  07  Sunshine
180.76.15.27,baiduspider-180-76-15-27.crawl.baidu.com,China  22  Beijing
