# Generated by http://www.infobyip.com/ipbulklookup.php at 20160104 08:01:16
IP,Domain,Location
202.162.74.172,,Australia  07  Hawthorn
49.196.133.174,pa49-196-133-174.pa.vic.optusnet.com.au,Australia  08  Perth
220.244.72.70,220-244-72-70.tpgi.com.au,Australia  04  Brisbane
10.68.66.6,,Private network
146.195.111.31,,Australia  08  Leeming
59.167.240.7,mail.ngssuper.com.au,Australia  02  Sydney
120.151.46.166,goldfi21.lnk.telstra.net,Australia  08  East Perth
175.32.175.9,,Australia  07  Melbourne
195.154.207.146,195-154-207-146.rev.poneytelecom.eu,France
1.144.97.96,,Australia  02  Sydney
60.231.182.50,CPE-60-231-182-50.lns4.dav.bigpond.net.au,Australia  06  Launceston
10.100.8.213,,Private network
182.255.99.70,exch01.mackillop.tas.edu.au,Australia  06  Howrah
103.241.148.65,mail.awu.org.au,Australia  04  Brisbane
1.136.97.2,,Australia  07  Melbourne
89.216.122.22,cable-89-216-122-22.static.sbb.rs,Serbia  02  Novi Sad
146.195.111.35,,Australia  08  Leeming
203.28.166.2,,Australia  02  Sydney
121.45.139.102,,Australia  05  Adelaide
121.223.155.4,CPE-121-223-155-4.lns2.bat.bigpond.net.au,Australia  06  Taroona
58.161.106.101,CPE-58-161-106-101.kybq1.win.bigpond.net.au,Australia
120.21.128.118,,Australia  07  Caulfield
84.228.111.69,IGLD-84-228-111-69.inter.net.il,Israel
1.144.97.73,,Australia  02  Sydney
182.239.183.4,182-239-183-4.ip.adam.com.au,Australia  05  Modbury
203.111.137.49,,Australia  07  Melbourne
203.206.167.126,203-206-167-126.perm.iinet.net.au,Australia  02  Sydney
1.129.97.80,,Australia  02  Sydney
203.217.56.73,203-217-56-73.perm.iinet.net.au,Australia  07  Collingwood
124.150.50.55,dsl-124-150-50-55.dyn.iinet.net.au,Australia  07  Brunswick
1.152.97.38,,Australia  07  Carnegie
1.136.96.247,,Australia  07  Melbourne
10.144.13.28,,Private network
83.223.122.23,83-223-122-23.as29017.net,United Kingdom
1.144.96.110,,Australia  02  Sydney
66.249.69.112,crawl-66-249-69-112.googlebot.com,United States  CA  Mountain View
66.249.69.96,crawl-66-249-69-96.googlebot.com,United States  CA  Mountain View
203.87.3.178,203-87-3-178.static.tpgi.com.au,Australia  07  Melbourne
124.148.20.20,gateway.comtel.com.au,Australia  04  Toowong
203.0.149.116,,Australia
68.180.229.152,b115318.yse.yahoo.net,United States  CA  Sunnyvale
147.69.168.26,,Australia  06  Devonport
66.249.73.130,crawl-66-249-73-130.googlebot.com,United States  CA  Mountain View
66.249.73.254,crawl-66-249-73-254.googlebot.com,United States  CA  Mountain View
101.179.23.182,cpe-101-179-23-182.qb01.dyn.asp.telstra.net,Australia  04  Aspley
58.106.129.179,d58-106-129-179.rdl802.qld.optusnet.com.au,Australia  04  Brisbane
49.255.247.100,ip-100.247.255.49.VOCUS.net.au,Australia  04  Brisbane
1.129.96.252,,Australia  02  Sydney
1.152.96.124,,Australia  07  Carnegie
