# Generated by http://www.infobyip.com/ipbulklookup.php at 20160104 08:01:20
IP,Domain,Location
115.166.63.157,115-166-63-157.dyn.iinet.net.au,Australia  08  Bicton
1.144.96.145,,Australia  02  Sydney
193.201.227.142,,Ukraine
101.190.33.15,,Australia  02  Adamstown
210.84.13.135,210-84-13-135.dyn.iinet.net.au,Australia  07  Melbourne
120.21.81.62,,Australia  07  Melbourne
106.69.207.255,106-69-207-bcast.dyn.iinet.net.au,Australia  08  Perth
110.175.136.94,110-175-136-94.static.tpgi.com.au,Australia  08  Wembley
220.253.231.3,220-253-231-3.dyn.iinet.net.au,Australia
49.183.70.176,pa49-183-70-176.pa.vic.optusnet.com.au,Australia  07  Lalor
203.191.199.158,mail.lucrf.com.au,Australia  07  South Melbourne
202.74.169.34,202-74-169-34.cep.zetta.net.au,Australia  08  Perth
146.195.81.96,,Australia  08  East Perth
140.159.2.247,,Australia  07  Melbourne
220.240.164.13,220-240-164-13.static.tpgi.com.au,Australia  07  Footscray
58.110.104.20,d58-110-104-20.meb800.vic.optusnet.com.au,Australia  07  Box Hill
66.249.73.139,crawl-66-249-73-139.googlebot.com,United States  CA  Mountain View
114.143.104.34,,India
124.168.72.11,124-168-72-11.dyn.iinet.net.au,Australia  07  Ballarat
165.118.1.50,proxyserver.health.wa.gov.au,Australia  08  Perth
193.201.225.129,,Ukraine
1.136.97.76,,Australia  07  Melbourne
174.129.237.157,ec2-174-129-237-157.compute-1.amazonaws.com,United States  VA  Ashburn
193.201.227.26,,Ukraine
118.211.238.237,ppp118-211-238-237.lns20.drw1.internode.on.net,Australia  03  Moulden
203.214.36.196,203-214-36-196.dyn.iinet.net.au,Australia  07  Southbank
58.7.97.22,58-7-97-22.dyn.iinet.net.au,Australia  08  Perth
193.201.225.58,,Ukraine
123.51.50.132,123-51-50-132.static.dsl.net.au,Australia  02  Young
58.104.5.12,d58-104-5-12.sbr802.nsw.optusnet.com.au,Australia  02  Sydney
216.145.5.42,www.whois.sc,United States  WA  Seattle
58.107.74.91,d58-107-74-91.mit800.act.optusnet.com.au,Australia  01  Kingston
54.164.87.189,ec2-54-164-87-189.compute-1.amazonaws.com,United States  VA  Ashburn
116.212.246.61,116.212.246.61.static.amnet.net.au,Australia
101.188.41.19,,Australia  07  Hallam
188.165.15.237,boson057.ahrefs.com,France
167.114.156.198,ns514167.ip-167-114-156.net,Canada  QC  Montréal
150.70.173.12,150-70-173-12.trendmicro.com,Japan
58.96.56.57,57.56.96.58.static.exetel.com.au,Australia  04  Brisbane
202.161.91.114,202-161-91-114.static.tpgi.com.au,Australia  07  Prahran
192.253.248.17,,Australia  02  Sydney
124.170.200.251,124-170-200-251.dyn.iinet.net.au,Australia  02  Baulkham Hills
120.149.130.200,CPE-120-149-130-200.lflg1.win.bigpond.net.au,Australia  07  Saint Albans
124.149.99.68,124-149-99-68.dyn.iinet.net.au,Australia  02  Lane Cove
14.2.93.148,ppp14-2-93-148.lns21.adl6.internode.on.net,Australia  05  Adelaide
66.220.146.30,,United States  CA  Menlo Park
69.171.228.116,,United States  CA  Menlo Park
66.249.69.104,crawl-66-249-69-104.googlebot.com,United States  CA  Mountain View
120.149.166.18,CPE-120-149-166-18.lflg3.vic.bigpond.net.au,Australia
58.107.71.60,d58-107-71-60.mit800.act.optusnet.com.au,Australia  01  Evatt
