# Generated by http://www.infobyip.com/ipbulklookup.php at 20160104 08:01:07
IP,Domain,Location
209.133.77.169,209.133.77.169.T01713-01.above.net,United States
50.23.253.187,vanadium.mailguard.com.au,United States  TX  Dallas
67.228.17.186,caesium.mailguard.com.au,United States  TX  Dallas
184.173.252.43,neodymium.mailguard.com.au,United States  TX  Dallas
203.57.131.37,,Australia  08  Kalgoorlie
10.42.2.148,,Private network
202.40.0.146,customer.node1.com.au,Australia  08  Geraldton
70.39.157.193,,United States
89.145.108.202,89-145-108-202.as29017.net,United Kingdom
70.39.157.194,,United States
173.192.120.186,polonium.mailguard.com.au,United States  TX  Dallas
83.223.122.5,83-223-122-5.as29017.net,United Kingdom
89.145.108.203,89-145-108-203.as29017.net,United Kingdom
70.39.157.192,,United States
83.223.122.10,83-223-122-10.as29017.net,United Kingdom
74.86.19.26,promethium.mailguard.com.au,United States  TX  Dallas
70.39.157.196,,United States
83.223.122.14,83-223-122-14.as29017.net,United Kingdom
173.192.120.187,mercury.mailguard.com.au,United States  TX  Dallas
133.130.58.190,v133-130-58-190.a013.g.tyo1.static.conoha.io,Japan
209.133.77.167,209.133.77.167.T01713-01.above.net,United States
10.19.101.47,,Private network
146.195.111.33,,Australia  08  Leeming
180.76.15.139,baiduspider-180-76-15-139.crawl.baidu.com,China  22  Beijing
203.46.10.108,203-46-10-108.tpips.telstra.com,Australia  08  Forrestfield
202.58.224.60,,Australia  08  Beechboro
180.76.15.5,baiduspider-180-76-15-5.crawl.baidu.com,China  22  Beijing
120.16.234.57,,Australia  08  Yangebup
121.221.6.243,CPE-121-221-6-243.lns1.wel.bigpond.net.au,Australia  08  Morley
180.76.15.160,baiduspider-180-76-15-160.crawl.baidu.com,China  22  Beijing
120.145.43.99,CPE-120-145-43-99.lnse2.wel.bigpond.net.au,Australia  08  Perth
180.76.15.147,baiduspider-180-76-15-147.crawl.baidu.com,China  22  Beijing
180.76.15.10,baiduspider-180-76-15-10.crawl.baidu.com,China  22  Beijing
180.76.15.151,baiduspider-180-76-15-151.crawl.baidu.com,China  22  Beijing
122.109.109.200,d122-109-109-200.per800.wa.optusnet.com.au,Australia  08  Perth
180.76.15.8,baiduspider-180-76-15-8.crawl.baidu.com,China  22  Beijing
1.136.96.170,,Australia  07  Melbourne
110.141.181.95,,Australia  08  Connolly
58.7.69.223,58-7-69-223.dyn.iinet.net.au,Australia  08  Perth
10.70.64.26,,Private network
180.76.15.143,baiduspider-180-76-15-143.crawl.baidu.com,China  22  Beijing
211.31.11.254,c211-31-11-254.rochd5.qld.optusnet.com.au,Australia  04  Brisbane
139.130.205.54,cityof235.lnk.telstra.net,Australia  08  Safety Bay
203.161.120.119,203.161.120.119.static.amnet.net.au,Australia  08  Heathridge
146.195.186.25,,Australia
116.212.205.98,exchange2007.sstuwa.org.au,Australia  08  Perth
203.27.5.17,ns.cityofperth.wa.gov.au,Australia  08  Burswood
180.76.15.156,baiduspider-180-76-15-156.crawl.baidu.com,China  22  Beijing
180.76.15.24,baiduspider-180-76-15-24.crawl.baidu.com,China  22  Beijing
203.213.0.203,corp.tpgtelecom.com.au,Australia  02  Sydney
